services:
  web:
    container_name: classes-control
    image: node:20.10.0
    working_dir: /app/web
    volumes:
      - './web:/app/web'
    ports:
      - '3000:3000'
    command: ['npm', 'run', 'dev']