services:
  web:
    container_name: ${PROJECT_NAME}-web
    image: node:20.10.0
    working_dir: /app/web
    volumes:
      - './web:/app/web'
    ports:
      - '3000:3000'
    env_file:
      - .env
    command: ['npm', 'run', 'dev']

#    db:
#      container_name: ${PROJECT_NAME}-db
#      image: postgres:16
#      environment: